'use client';

import React, { useState, useEffect } from 'react';
import {
  Container,
  Typography,
  Box,
  Paper,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
} from '@mui/material';
import Layout from '@/components/Layout';

export default function TruckRevenueReportPage() {
  const [truckRevenue, setTruckRevenue] = useState<any[]>([]);

  useEffect(() => {
    fetchTruckRevenue();
  }, []);

  const fetchTruckRevenue = async () => {
    try {
      const [tripsRes, trucksRes] = await Promise.all([
        fetch('/api/trips'),
        fetch('/api/trucks'),
      ]);

      const trips = await tripsRes.json();
      const trucks = await trucksRes.json();

      const tripsArray = Array.isArray(trips) ? trips : [];
      const trucksArray = Array.isArray(trucks) ? trucks : [];

      // Calculate revenue per truck
      const revenueByTruck = trucksArray.map((truck: any) => {
        const truckTrips = tripsArray.filter((t: any) => t.truck_id === truck.id);
        const revenue = truckTrips.reduce((sum: number, t: any) => sum + (t.freight_amount || 0), 0);
        return {
          truck_number: truck.truck_number,
          tripCount: truckTrips.length,
          revenue,
        };
      });

      setTruckRevenue(revenueByTruck.sort((a, b) => b.revenue - a.revenue));
    } catch (err) {
      console.error('Failed to fetch truck revenue:', err);
    }
  };

  return (
    <Layout>
      <Container maxWidth="lg">
        <Box sx={{ my: 4 }}>
          <Typography variant="h4" sx={{ fontWeight: 700, color: '#0D3B66', mb: 1 }}>
            Truck Revenue Report
          </Typography>
          <Typography variant="body2" color="text.secondary" sx={{ mb: 4 }}>
            Track income generated by each truck
          </Typography>

          <Paper elevation={3}>
            <TableContainer>
              <Table>
                <TableHead sx={{ bgcolor: '#FAFAFA' }}>
                  <TableRow>
                    <TableCell sx={{ fontWeight: 600 }}>Truck Number</TableCell>
                    <TableCell sx={{ fontWeight: 600 }} align="right">Total Trips</TableCell>
                    <TableCell sx={{ fontWeight: 600 }} align="right">Total Revenue</TableCell>
                  </TableRow>
                </TableHead>
                <TableBody>
                  {truckRevenue.map((truck, index) => (
                    <TableRow key={index} hover>
                      <TableCell>{truck.truck_number}</TableCell>
                      <TableCell align="right">{truck.tripCount}</TableCell>
                      <TableCell align="right" sx={{ fontWeight: 600, color: '#EA7847' }}>
                        ₹{truck.revenue.toLocaleString()}
                      </TableCell>
                    </TableRow>
                  ))}
                  {truckRevenue.length === 0 && (
                    <TableRow>
                      <TableCell colSpan={3} align="center" sx={{ py: 4 }}>
                        No data available
                      </TableCell>
                    </TableRow>
                  )}
                </TableBody>
              </Table>
            </TableContainer>
          </Paper>
        </Box>
      </Container>
    </Layout>
  );
}
